### ISSUE TITLE
打开个网页，进程就太多了

### ISSUE THREAD

**Issue by pexcn** [examplecode/mproxy#12]
![01](https://cloud.githubusercontent.com/assets/4590439/14580623/b30e604c-0405-11e6-996f-53bd97c57ec2.png)

请问是不是开一条连接就开一条进程了？windows下也是这样

**Comment by hellojukay** [comment]
这个你可以看他的源代码，打开一个网页会加载css和js，还有ajax请求。会建立很多个http连接。而作业在处理http的时候，是读数据一个进程，写数据一个进程，一个http就是四个进程。
